### ISSUE TITLE
Create a Driver/Webdriver class

### ISSUE THREAD

**Issue by IvanYingX** [IvanYingX/Linkedin-Scraper-Project#5]
Create a class with different methods, in which each method allows you to easily navigate the website

**Comment by MateuszBar** [comment]
I've created a template for the main functionality of the class with TODOs for each function, inside of main.py in the main branch. If I've missed any basic functions feel free to add them

**Comment by MateuszBar** [comment]
Added functionality to accept_cookies and log_me_in methods, script now loads webpage, accepts cookies and logs the user into the website
